In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [3]:
df = pd.read_parquet('df_cleaned.parquet')

In [4]:
df

,user_id,age,gender,country,urban_rural,income_level,employment_status,education_level,relationship_status,has_children,...,checkout_abandonments_per_month,purchase_conversion_rate,app_usage_frequency,notification_response_rate,account_age_months,last_purchase_date,social_sharing_frequency,premium_subscription,return_rate,churn
0,1,56,Female,Germany,Suburban,90860,Self-employed,Associate Degree,Single,0,...,2,62,7,74,19,2025-06-22,6,1,50,0
1,2,69,Male,Japan,Suburban,35423,Unemployed,Bachelor,Single,1,...,7,54,5,23,8,2026-07-25,3,0,37,0
2,3,46,Female,India,Urban,21467,Self-employed,Associate Degree,Married,1,...,3,33,7,12,13,2026-02-26,6,0,53,0
3,4,32,Male,Canada,Urban,41770,Self-employed,Bachelor,Widowed,0,...,9,26,4,19,9,2026-10-27,7,0,98,0
4,5,60,Female,Japan,Urban,183882,Employed,Associate Degree,Widowed,1,...,0,18,7,30,3,2026-06-23,3,0,86,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999996,36,Female,France,Urban,192880,Student,Master,In a relationship,0,...,3,26,2,50,21,2025-06-27,2,1,93,0
999996,999997,37,Male,Canada,Urban,197111,Unemployed,Master,Divorced,0,...,9,31,5,78,15,2025-06-05,7,1,97,0
999997,999998,71,Male,UK,Urban,171275,Unemployed,Bachelor,Married,1,...,5,19,7,8,16,2026-09-25,5,0,96,0
999998,999999,30,Female,Germany,Urban,124983,Employed,High School,Single,0,...,2,56,5,8,11,2026-10-25,2,0,46,0
999999,1000000,61,Male,China,Rural,65396,Student,Bachelor,In a relationship,1,...,10,79,0,64,1,2025-12-17,5,0,43,0

In [5]:
df.describe()

,user_id,age,income_level,has_children,household_size,weekly_purchases,monthly_spend,cart_abandonment_rate,review_writing_frequency,average_order_value,...,cart_items_average,checkout_abandonments_per_month,purchase_conversion_rate,app_usage_frequency,notification_response_rate,account_age_months,social_sharing_frequency,premium_subscription,return_rate,churn
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,...,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,500000.500000,49.003377,104994.565463,0.399426,5.505323,9.993011,2498.775654,40.212257,3.450584,255.031632,...,5.494336,4.997523,50.001442,3.498840,49.989012,12.509560,3.593763,0.359415,50.004949,0.076803
std,288675.278933,18.193959,54851.476652,0.489781,2.873725,6.055124,1444.208674,25.433343,1.856725,141.708466,...,2.870467,3.162831,29.163437,2.291567,29.151948,6.922197,1.932566,0.479829,29.159616,0.266279
min,1.000000,18.000000,10000.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,10.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,250000.750000,33.000000,57466.000000,0.000000,3.000000,5.000000,1249.000000,18.000000,2.000000,132.000000,...,3.000000,2.000000,25.000000,1.000000,25.000000,7.000000,2.000000,0.000000,25.000000,0.000000
50%,500000.500000,49.000000,105013.000000,0.000000,6.000000,10.000000,2498.000000,40.000000,3.000000,255.000000,...,5.000000,5.000000,50.000000,3.000000,50.000000,13.000000,4.000000,0.000000,50.000000,0.000000
75%,750000.250000,65.000000,152497.000000,1.000000,8.000000,15.000000,3750.000000,62.000000,5.000000,378.000000,...,8.000000,8.000000,75.000000,6.000000,75.000000,19.000000,5.000000,1.000000,75.000000,0.000000
max,1000000.000000,80.000000,200000.000000,1.000000,10.000000,20.000000,5000.000000,90.000000,8.000000,500.000000,...,10.000000,10.000000,100.000000,7.000000,100.000000,24.000000,8.000000,1.000000,100.000000,1.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 61 columns):
 #   Column                           Non-Null Count    Dtype
---  ------                           --------------    -----
 0   user_id                          1000000 non-null  int64
 1   age                              1000000 non-null  int64
 2   gender                           1000000 non-null  object
 3   country                          1000000 non-null  object
 4   urban_rural                      1000000 non-null  object
 5   income_level                     1000000 non-null  int64
 6   employment_status                1000000 non-null  object
 7   education_level                  1000000 non-null  object
 8   relationship_status              1000000 non-null  object
 9   has_children                     1000000 non-null  int64
 10  household_size                   1000000 non-null  int64
 11  occupation                       1000000 non-null  object
 12  ethnicity                        1000000 non-null  object
 13  language_preference              1000000 non-null  object
 14  device_type                      1000000 non-null  object
 15  weekly_purchases                 1000000 non-null  int64
 16  monthly_spend                    1000000 non-null  int64
 17  cart_abandonment_rate            1000000 non-null  int64
 18  review_writing_frequency         1000000 non-null  int64
 19  average_order_value              1000000 non-null  int64
 20  preferred_payment_method         1000000 non-null  object
 21  coupon_usage_frequency           1000000 non-null  int64
 22  loyalty_program_member           1000000 non-null  int64
 23  referral_count                   1000000 non-null  int64
 24  product_category_preference      1000000 non-null  object
 25  shopping_time_of_day             1000000 non-null  object
 26  weekend_shopper                  1000000 non-null  int64
 27  impulse_purchases_per_month      1000000 non-null  int64
 28  browse_to_buy_ratio              1000000 non-null  int64
 29  return_frequency                 1000000 non-null  int64
 30  budgeting_style                  1000000 non-null  object
 31  brand_loyalty_score              1000000 non-null  int64
 32  impulse_buying_score             1000000 non-null  int64
 33  environmental_consciousness      1000000 non-null  int64
 34  health_conscious_shopping        1000000 non-null  int64
 35  travel_frequency                 1000000 non-null  int64
 36  hobby_count                      1000000 non-null  int64
 37  social_media_influence_score     1000000 non-null  int64
 38  reading_habits                   1000000 non-null  int64
 39  exercise_frequency               1000000 non-null  int64
 40  stress_from_financial_decisions  1000000 non-null  int64
 41  overall_stress_level             1000000 non-null  int64
 42  sleep_quality                    1000000 non-null  int64
 43  physical_activity_level          1000000 non-null  int64
 44  mental_health_score              1000000 non-null  int64
 45  daily_session_time_minutes       1000000 non-null  int64
 46  product_views_per_day            1000000 non-null  int64
 47  ad_views_per_day                 1000000 non-null  int64
 48  ad_clicks_per_day                1000000 non-null  int64
 49  wishlist_items_count             1000000 non-null  int64
 50  cart_items_average               1000000 non-null  int64
 51  checkout_abandonments_per_month  1000000 non-null  int64
 52  purchase_conversion_rate         1000000 non-null  int64
 53  app_usage_frequency              1000000 non-null  int64
 54  notification_response_rate       1000000 non-null  int64
 55  account_age_months               1000000 non-null  int64
 56  last_purchase_date               1000000 non-null  object
 57  social_sharing_frequency         1000000 non-null  int64
 58  premium_subscription             1000000 non-null  int64
 59  return_rate                      1000000 non-null  int64
 60  churn                            1000000 non-null  int64
dtypes: int64(46), object(15)
memory usage: 465.4+ MB

In [7]:
#remove user_id column
df.drop(columns = ['user_id'], inplace = True)

In [13]:
pd.set_option('display.max_columns', None) #show all columns
df.describe(exclude= ['O']) # Describe all numerical columns

,age,income_level,has_children,household_size,weekly_purchases,monthly_spend,cart_abandonment_rate,review_writing_frequency,average_order_value,coupon_usage_frequency,loyalty_program_member,referral_count,weekend_shopper,impulse_purchases_per_month,browse_to_buy_ratio,return_frequency,brand_loyalty_score,impulse_buying_score,environmental_consciousness,health_conscious_shopping,travel_frequency,hobby_count,social_media_influence_score,reading_habits,exercise_frequency,stress_from_financial_decisions,overall_stress_level,sleep_quality,physical_activity_level,mental_health_score,daily_session_time_minutes,product_views_per_day,ad_views_per_day,ad_clicks_per_day,wishlist_items_count,cart_items_average,checkout_abandonments_per_month,purchase_conversion_rate,app_usage_frequency,notification_response_rate,account_age_months,social_sharing_frequency,premium_subscription,return_rate,churn
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.00000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,49.003377,104994.565463,0.399426,5.505323,9.993011,2498.775654,40.212257,3.450584,255.031632,2.002277,0.499818,5.004928,0.500035,3.290010,55.000136,6.000272,4.999277,4.998423,5.005931,0.500046,5.993844,2.499994,5.004101,11.995084,3.501375,4.998577,4.999507,6.498723,4.993603,5.002855,60.014414,25.018014,10.001036,2.498174,9.99766,5.494336,4.997523,50.001442,3.498840,49.989012,12.509560,3.593763,0.359415,50.004949,0.076803
std,18.193959,54851.476652,0.489781,2.873725,6.055124,1444.208674,25.433343,1.856725,141.708466,1.415410,0.500000,3.162728,0.500000,1.819482,26.268341,3.741100,3.161723,3.216289,3.164084,0.500000,3.740345,1.708171,3.159897,7.209871,2.291257,3.165220,3.215078,1.706388,3.162574,3.160619,34.939233,14.721810,6.056522,1.708079,6.05453,2.870467,3.162831,29.163437,2.291567,29.151948,6.922197,1.932566,0.479829,29.159616,0.266279
min,18.000000,10000.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,33.000000,57466.000000,0.000000,3.000000,5.000000,1249.000000,18.000000,2.000000,132.000000,1.000000,0.000000,2.000000,0.000000,2.000000,32.000000,3.000000,2.000000,2.000000,2.000000,0.000000,3.000000,1.000000,2.000000,6.000000,2.000000,2.000000,2.000000,5.000000,2.000000,2.000000,30.000000,12.000000,5.000000,1.000000,5.00000,3.000000,2.000000,25.000000,1.000000,25.000000,7.000000,2.000000,0.000000,25.000000,0.000000
50%,49.000000,105013.000000,0.000000,6.000000,10.000000,2498.000000,40.000000,3.000000,255.000000,2.000000,0.000000,5.000000,1.000000,3.000000,55.000000,6.000000,5.000000,5.000000,5.000000,1.000000,6.000000,2.000000,5.000000,12.000000,4.000000,5.000000,5.000000,6.000000,5.000000,5.000000,60.000000,25.000000,10.000000,2.000000,10.00000,5.000000,5.000000,50.000000,3.000000,50.000000,13.000000,4.000000,0.000000,50.000000,0.000000
75%,65.000000,152497.000000,1.000000,8.000000,15.000000,3750.000000,62.000000,5.000000,378.000000,3.000000,1.000000,8.000000,1.000000,5.000000,78.000000,9.000000,8.000000,8.000000,8.000000,1.000000,9.000000,4.000000,8.000000,18.000000,6.000000,8.000000,8.000000,8.000000,8.000000,8.000000,90.000000,38.000000,15.000000,4.000000,15.00000,8.000000,8.000000,75.000000,6.000000,75.000000,19.000000,5.000000,1.000000,75.000000,0.000000
max,80.000000,200000.000000,1.000000,10.000000,20.000000,5000.000000,90.000000,8.000000,500.000000,4.000000,1.000000,10.000000,1.000000,7.000000,100.000000,12.000000,10.000000,10.000000,10.000000,1.000000,12.000000,5.000000,10.000000,24.000000,7.000000,10.000000,10.000000,9.000000,10.000000,10.000000,120.000000,50.000000,20.000000,5.000000,20.00000,10.000000,10.000000,100.000000,7.000000,100.000000,24.000000,8.000000,1.000000,100.000000,1.000000

In [14]:
df.describe(include = ['O']) # Describe all categorical columns

,gender,country,urban_rural,employment_status,education_level,relationship_status,occupation,ethnicity,language_preference,device_type,preferred_payment_method,product_category_preference,shopping_time_of_day,budgeting_style,last_purchase_date
count,1000000,1000000,1000000,1000000,1000000,1000000,1000000,1000000,1000000,1000000,1000000,1000000,1000000,1000000,1000000
unique,4,10,3,5,5,5,8,5,6,3,6,8,4,3,731
top,Male,Brazil,Urban,Retired,Bachelor,Divorced,Other,Asian,German,Mobile,Apple Pay,Beauty,Evening,Moderate,2026-08-09
freq,480132,100476,500226,200246,299953,200675,125591,201102,167557,600247,166983,125409,250185,333771,1508

In [18]:
target_column = 'churn'

In [20]:
#separating/ categorising columns

numerical_columns = ['age', 'income_level', 'household_size', 'weekly_purchases' , 'monthly_spend' , 'cart_abandonment_rate' , 
                     'review_writing_frequency' , 'average_order_value' , 'coupon_usage_frequency' , 'referral_count' , 
                     'impulse_purchases_per_month' , 'browse_to_buy_ratio' , 'return_frequency' , 'brand_loyalty_score' , 
                     'impulse_buying_score' , 'environmental_consciousness' , 'travel_frequency' , 'hobby_count', 
                     'social_media_influence_score' ,'reading_habits' , 'exercise_frequency' , 'stress_from_financial_decisions' , 
                     'overall_stress_level' , 'sleep_quality' , 'physical_activity_level' , 'mental_health_score' , 'daily_session_time_minutes' , 
                     'product_views_per_day' , 'ad_views_per_day' , 'ad_clicks_per_day' , 'wishlist_items_count' , 'cart_items_average' , 
                     'checkout_abandonments_per_month' , 'purchase_conversion_rate' , 'app_usage_frequency' , 'notification_response_rate' , 
                     'account_age_months' , 'social_sharing_frequency' ,'return_rate']

categorical_columns = [
   'gender', 'country', 'urban_rural', 'employment_status', 'education_level',
'relationship_status', 'has_children', 'occupation', 'ethnicity',
'language_preference', 'device_type', 'preferred_payment_method', 
'product_category_preference', 'shopping_time_of_day','budgeting_style'
]

boolean_columns = ['has_children', 'loyalty_program_member', 'weekend_shopper', 'health_conscious_shopping', 'premium_subscription']

date_column = ['last_purchase_date']

all_columns = numerical_columns + categorical_columns + boolean_columns + [date_column] + [target_column]

In [26]:
#perform encoding on categorical columns
encoder = LabelEncoder()
for each_col in categorical_columns:
    df[each_col] = encoder.fit_transform(df[each_col])

In [27]:
df.head()

,age,gender,country,urban_rural,income_level,employment_status,education_level,relationship_status,has_children,household_size,occupation,ethnicity,language_preference,device_type,weekly_purchases,monthly_spend,cart_abandonment_rate,review_writing_frequency,average_order_value,preferred_payment_method,coupon_usage_frequency,loyalty_program_member,referral_count,product_category_preference,shopping_time_of_day,weekend_shopper,impulse_purchases_per_month,browse_to_buy_ratio,return_frequency,budgeting_style,brand_loyalty_score,impulse_buying_score,environmental_consciousness,health_conscious_shopping,travel_frequency,hobby_count,social_media_influence_score,reading_habits,exercise_frequency,stress_from_financial_decisions,overall_stress_level,sleep_quality,physical_activity_level,mental_health_score,daily_session_time_minutes,product_views_per_day,ad_views_per_day,ad_clicks_per_day,wishlist_items_count,cart_items_average,checkout_abandonments_per_month,purchase_conversion_rate,app_usage_frequency,notification_response_rate,account_age_months,last_purchase_date,social_sharing_frequency,premium_subscription,return_rate,churn
0,56,0,5,1,90860,2,0,3,0,5,3,4,0,1,4,2405,0,3,445,5,3,1,8,4,2,1,2,12,1,2,8,1,4,1,8,0,2,22,4,0,0,5,2,7,100,38,14,1,5,10,2,62,7,74,19,2025-06-22,6,1,50,0
1,69,1,7,1,35423,4,1,3,1,2,2,4,4,1,13,3651,28,6,179,4,0,1,3,4,0,1,3,93,12,0,4,3,7,1,4,1,5,14,4,4,5,9,8,5,28,19,9,2,17,5,7,54,5,23,8,2026-07-25,3,0,37,0
2,46,0,6,2,21467,2,0,2,1,6,3,4,3,1,10,2045,14,1,26,5,0,0,10,0,0,0,2,68,5,1,2,2,5,1,6,2,0,14,4,0,0,8,10,10,61,38,1,4,18,3,3,33,7,12,13,2026-02-26,6,0,53,0
3,32,1,2,2,41770,2,1,4,0,4,1,3,3,0,16,1611,11,2,403,2,2,1,0,4,0,1,3,74,2,1,3,2,0,1,12,1,1,15,0,2,0,9,2,1,78,35,9,2,8,5,9,26,4,19,9,2026-10-27,7,0,98,0
4,60,0,7,2,183882,0,0,4,1,9,6,1,0,0,17,3476,57,3,68,0,0,1,0,4,1,0,6,34,12,0,7,8,9,0,6,5,10,20,5,8,10,5,3,2,27,50,16,0,10,8,0,18,7,30,3,2026-06-23,3,0,86,0

In [28]:
#drop date column
df = df.drop('last_purchase_date', axis=1)

In [29]:
df.head()

,age,gender,country,urban_rural,income_level,employment_status,education_level,relationship_status,has_children,household_size,occupation,ethnicity,language_preference,device_type,weekly_purchases,monthly_spend,cart_abandonment_rate,review_writing_frequency,average_order_value,preferred_payment_method,coupon_usage_frequency,loyalty_program_member,referral_count,product_category_preference,shopping_time_of_day,weekend_shopper,impulse_purchases_per_month,browse_to_buy_ratio,return_frequency,budgeting_style,brand_loyalty_score,impulse_buying_score,environmental_consciousness,health_conscious_shopping,travel_frequency,hobby_count,social_media_influence_score,reading_habits,exercise_frequency,stress_from_financial_decisions,overall_stress_level,sleep_quality,physical_activity_level,mental_health_score,daily_session_time_minutes,product_views_per_day,ad_views_per_day,ad_clicks_per_day,wishlist_items_count,cart_items_average,checkout_abandonments_per_month,purchase_conversion_rate,app_usage_frequency,notification_response_rate,account_age_months,social_sharing_frequency,premium_subscription,return_rate,churn
0,56,0,5,1,90860,2,0,3,0,5,3,4,0,1,4,2405,0,3,445,5,3,1,8,4,2,1,2,12,1,2,8,1,4,1,8,0,2,22,4,0,0,5,2,7,100,38,14,1,5,10,2,62,7,74,19,6,1,50,0
1,69,1,7,1,35423,4,1,3,1,2,2,4,4,1,13,3651,28,6,179,4,0,1,3,4,0,1,3,93,12,0,4,3,7,1,4,1,5,14,4,4,5,9,8,5,28,19,9,2,17,5,7,54,5,23,8,3,0,37,0
2,46,0,6,2,21467,2,0,2,1,6,3,4,3,1,10,2045,14,1,26,5,0,0,10,0,0,0,2,68,5,1,2,2,5,1,6,2,0,14,4,0,0,8,10,10,61,38,1,4,18,3,3,33,7,12,13,6,0,53,0
3,32,1,2,2,41770,2,1,4,0,4,1,3,3,0,16,1611,11,2,403,2,2,1,0,4,0,1,3,74,2,1,3,2,0,1,12,1,1,15,0,2,0,9,2,1,78,35,9,2,8,5,9,26,4,19,9,7,0,98,0
4,60,0,7,2,183882,0,0,4,1,9,6,1,0,0,17,3476,57,3,68,0,0,1,0,4,1,0,6,34,12,0,7,8,9,0,6,5,10,20,5,8,10,5,3,2,27,50,16,0,10,8,0,18,7,30,3,3,0,86,0

In [31]:
#perform feature selection through checking multicollinearity with VIF
X = df.drop(['churn'], axis =1)

In [33]:
corr_matrix = X.corr()

In [34]:
# Identify pairs of features with high collinearity (correlation > 0.8 or < -0.8).
high_corr_features = [(col1, col2, corr_matrix.loc[col1, col2])
                     for col1 in corr_matrix.columns
                     for col2 in corr_matrix.columns
                     if col1 != col2 and abs(corr_matrix.loc[col1, col2]) > 0.8]

In [35]:
# Convert to a DataFrame for better visualization.
collinearity_df = pd.DataFrame(high_corr_features, columns=["Feature 1", "Feature 2", "Correlation"])
print("\nHighly Correlated Features:\n", collinearity_df)

Highly Correlated Features:
                           Feature 1                        Feature 2  \
0             cart_abandonment_rate      impulse_purchases_per_month
1             cart_abandonment_rate             impulse_buying_score
2             cart_abandonment_rate  stress_from_financial_decisions
3             cart_abandonment_rate             overall_stress_level
4       impulse_purchases_per_month            cart_abandonment_rate
5       impulse_purchases_per_month             impulse_buying_score
6       impulse_purchases_per_month  stress_from_financial_decisions
7              impulse_buying_score            cart_abandonment_rate
8              impulse_buying_score      impulse_purchases_per_month
9              impulse_buying_score  stress_from_financial_decisions
10             impulse_buying_score             overall_stress_level
11  stress_from_financial_decisions            cart_abandonment_rate
12  stress_from_financial_decisions      impulse_purchases_per_month
13  stress_from_financial_decisions             impulse_buying_score
14  stress_from_financial_decisions             overall_stress_level
15             overall_stress_level            cart_abandonment_rate
16             overall_stress_level             impulse_buying_score
17             overall_stress_level  stress_from_financial_decisions

    Correlation
0      0.850080
1      0.961469
2      0.940364
3      0.863500
4      0.850080
5      0.883329
6      0.809553
7      0.961469
8      0.883329
9      0.916233
10     0.841863
11     0.940364
12     0.809553
13     0.916233
14     0.916235
15     0.863500
16     0.841863
17     0.916235

In [36]:
# Compute Variance Inflation Factor (VIF) for each feature.
vif_data = pd.DataFrame()
vif_data["Feature"] = X.columns
vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]

In [37]:
# Print VIF values.
print("\nVariance Inflation Factor (VIF) for each feature:\n", vif_data)

Variance Inflation Factor (VIF) for each feature:
                             Feature        VIF
0                               age   9.249890
1                            gender   1.825344
2                           country   3.395887
3                       urban_rural   3.707296
4                      income_level   4.556275
5                 employment_status   2.960784
6                   education_level   3.944971
7               relationship_status   2.955791
8                      has_children   1.658383
9                    household_size   4.560539
10                       occupation   3.287484
11                        ethnicity   2.957765
12              language_preference   3.103512
13                      device_type   2.747273
14                 weekly_purchases   3.659502
15                    monthly_spend   3.915453
16            cart_abandonment_rate  65.331000
17         review_writing_frequency   4.935939
18              average_order_value   4.151104
19         preferred_payment_method   3.097876
20           coupon_usage_frequency   2.963378
21           loyalty_program_member   1.986494
22                   referral_count   3.447724
23      product_category_preference   3.279174
24             shopping_time_of_day   2.770458
25                  weekend_shopper   1.988053
26      impulse_purchases_per_month  19.326907
27              browse_to_buy_ratio   5.233487
28                 return_frequency   3.512683
29                  budgeting_style   2.475061
30              brand_loyalty_score   3.445292
31             impulse_buying_score  57.789703
32      environmental_consciousness   3.446046
33        health_conscious_shopping   1.987386
34                 travel_frequency   3.509320
35                      hobby_count   3.100068
36     social_media_influence_score   3.450210
37                   reading_habits   3.702652
38               exercise_frequency   3.285746
39  stress_from_financial_decisions  48.335776
40             overall_stress_level  21.290669
41                    sleep_quality  14.075179
42          physical_activity_level   3.437085
43              mental_health_score   3.449527
44       daily_session_time_minutes   3.875703
45            product_views_per_day   3.815162
46                 ad_views_per_day   3.662169
47                ad_clicks_per_day   3.096399
48             wishlist_items_count   3.660725
49               cart_items_average   4.556909
50  checkout_abandonments_per_month   3.440347
51         purchase_conversion_rate   3.865723
52              app_usage_frequency   3.281713
53       notification_response_rate   3.866785
54               account_age_months   4.176371
55         social_sharing_frequency   5.125203
56             premium_subscription   2.229711
57                      return_rate   3.867119

In [38]:
#remove 6 columns with VIF above 10 to mitigate multicollinearity
df = df.drop(columns = ['cart_abandonment_rate','impulse_purchases_per_month', 
                  'impulse_buying_score', 'stress_from_financial_decisions', 
                  'overall_stress_level', 'sleep_quality'])

In [39]:
df.to_parquet('df_fe.parquet', index=False)

In [40]:
df

,age,gender,country,urban_rural,income_level,employment_status,education_level,relationship_status,has_children,household_size,occupation,ethnicity,language_preference,device_type,weekly_purchases,monthly_spend,review_writing_frequency,average_order_value,preferred_payment_method,coupon_usage_frequency,loyalty_program_member,referral_count,product_category_preference,shopping_time_of_day,weekend_shopper,browse_to_buy_ratio,return_frequency,budgeting_style,brand_loyalty_score,environmental_consciousness,health_conscious_shopping,travel_frequency,hobby_count,social_media_influence_score,reading_habits,exercise_frequency,physical_activity_level,mental_health_score,daily_session_time_minutes,product_views_per_day,ad_views_per_day,ad_clicks_per_day,wishlist_items_count,cart_items_average,checkout_abandonments_per_month,purchase_conversion_rate,app_usage_frequency,notification_response_rate,account_age_months,social_sharing_frequency,premium_subscription,return_rate,churn
0,56,0,5,1,90860,2,0,3,0,5,3,4,0,1,4,2405,3,445,5,3,1,8,4,2,1,12,1,2,8,4,1,8,0,2,22,4,2,7,100,38,14,1,5,10,2,62,7,74,19,6,1,50,0
1,69,1,7,1,35423,4,1,3,1,2,2,4,4,1,13,3651,6,179,4,0,1,3,4,0,1,93,12,0,4,7,1,4,1,5,14,4,8,5,28,19,9,2,17,5,7,54,5,23,8,3,0,37,0
2,46,0,6,2,21467,2,0,2,1,6,3,4,3,1,10,2045,1,26,5,0,0,10,0,0,0,68,5,1,2,5,1,6,2,0,14,4,10,10,61,38,1,4,18,3,3,33,7,12,13,6,0,53,0
3,32,1,2,2,41770,2,1,4,0,4,1,3,3,0,16,1611,2,403,2,2,1,0,4,0,1,74,2,1,3,0,1,12,1,1,15,0,2,1,78,35,9,2,8,5,9,26,4,19,9,7,0,98,0
4,60,0,7,2,183882,0,0,4,1,9,6,1,0,0,17,3476,3,68,0,0,1,0,4,1,0,34,12,0,7,9,0,6,5,10,20,5,3,2,27,50,16,0,10,8,0,18,7,30,3,3,0,86,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,36,0,4,2,192880,3,3,1,0,5,6,0,4,1,15,279,3,374,4,4,0,3,6,0,0,59,12,0,1,3,1,3,5,3,7,6,1,6,39,46,17,1,10,4,3,26,2,50,21,2,1,93,0
999996,37,1,2,2,197111,4,3,0,0,8,7,2,3,0,10,773,4,156,3,2,1,0,5,3,1,29,3,0,7,3,1,2,3,5,17,4,0,3,5,41,11,0,4,10,9,31,5,78,15,7,1,97,0
999997,71,1,8,2,171275,4,1,2,1,1,0,2,2,2,11,387,4,156,2,3,0,2,4,3,1,63,8,1,4,0,1,0,1,10,21,7,5,2,27,31,6,3,15,6,5,19,7,8,16,5,0,96,0
999998,30,0,5,2,124983,0,2,3,0,8,6,4,0,1,1,114,1,269,0,2,1,8,0,3,1,100,7,1,0,8,1,9,0,10,11,1,1,3,67,30,16,3,3,4,2,56,5,8,11,2,0,46,0
999999,61,1,3,0,65396,3,1,1,1,9,4,0,1,1,5,392,2,261,2,4,1,9,3,2,0,45,9,0,6,8,1,11,5,3,13,5,5,4,106,48,18,4,13,10,10,79,0,64,1,5,0,43,0